// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: capture-screen-request.proto

package captureScreenRequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScreenCaptureService_ReceiveCapture_FullMethodName = "/screencapture.ScreenCaptureService/ReceiveCapture"
)

// ScreenCaptureServiceClient is the client API for ScreenCaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScreenCaptureServiceClient interface {
	ReceiveCapture(ctx context.Context, in *CaptureData, opts ...grpc.CallOption) (*CaptureAck, error)
}

type screenCaptureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScreenCaptureServiceClient(cc grpc.ClientConnInterface) ScreenCaptureServiceClient {
	return &screenCaptureServiceClient{cc}
}

func (c *screenCaptureServiceClient) ReceiveCapture(ctx context.Context, in *CaptureData, opts ...grpc.CallOption) (*CaptureAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureAck)
	err := c.cc.Invoke(ctx, ScreenCaptureService_ReceiveCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScreenCaptureServiceServer is the server API for ScreenCaptureService service.
// All implementations must embed UnimplementedScreenCaptureServiceServer
// for forward compatibility.
type ScreenCaptureServiceServer interface {
	ReceiveCapture(context.Context, *CaptureData) (*CaptureAck, error)
	mustEmbedUnimplementedScreenCaptureServiceServer()
}

// UnimplementedScreenCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScreenCaptureServiceServer struct{}

func (UnimplementedScreenCaptureServiceServer) ReceiveCapture(context.Context, *CaptureData) (*CaptureAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveCapture not implemented")
}
func (UnimplementedScreenCaptureServiceServer) mustEmbedUnimplementedScreenCaptureServiceServer() {}
func (UnimplementedScreenCaptureServiceServer) testEmbeddedByValue()                              {}

// UnsafeScreenCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScreenCaptureServiceServer will
// result in compilation errors.
type UnsafeScreenCaptureServiceServer interface {
	mustEmbedUnimplementedScreenCaptureServiceServer()
}

func RegisterScreenCaptureServiceServer(s grpc.ServiceRegistrar, srv ScreenCaptureServiceServer) {
	// If the following call pancis, it indicates UnimplementedScreenCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScreenCaptureService_ServiceDesc, srv)
}

func _ScreenCaptureService_ReceiveCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreenCaptureServiceServer).ReceiveCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScreenCaptureService_ReceiveCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreenCaptureServiceServer).ReceiveCapture(ctx, req.(*CaptureData))
	}
	return interceptor(ctx, in, info, handler)
}

// ScreenCaptureService_ServiceDesc is the grpc.ServiceDesc for ScreenCaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScreenCaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "screencapture.ScreenCaptureService",
	HandlerType: (*ScreenCaptureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveCapture",
			Handler:    _ScreenCaptureService_ReceiveCapture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capture-screen-request.proto",
}
